server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8082
spring:
  profiles: dev

---


server:
  port: 8083
spring:
  profiles: prod

---
#person:
#  lastName: zhangsan
#  age: 20
#  boss: false
#  birth: 2000/05/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - wangwu
#    - zhaoliu
#  dog:
#    name: Sam
#    age: 3